### ISSUE TITLE
Security group error during initial blueprint setup

### ISSUE THREAD

**Issue by marcustriplett** [cunningham-lab/neurocaas#115]
I'm facing the following security group error during the initial setup of a custom blueprint.

```
(neurocaas) marcustriplett@dyn-160-39-141-172 neurocaas % neurocaas-contrib remote start-session
No development instance detected. Resetting session.
(neurocaas) marcustriplett@dyn-160-39-141-172 neurocaas % neurocaas-contrib remote launch-devinstance --timeout 1 
checking image is available...
Traceback (most recent call last):
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/bin/neurocaas-contrib", line 8, in <module>
    sys.exit(main())
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/neurocaas_contrib/main.py", line 5, in main
    cli()
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/neurocaas_contrib/cli_commands.py", line 1363, in launch_devinstance
    ami.launch_devinstance(ami = amiid,volume_size = volumesize,timeout = timeout)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/neurocaas_contrib/remote.py", line 200, in launch_devinstance
    waiter.wait(ImageIds = [ami_id])
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/waiter.py", line 53, in wait
    Waiter.wait(self, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/waiter.py", line 313, in wait
    last_response=response
botocore.exceptions.WaiterError: Waiter ImageAvailable failed: Invalid id: "dlami18" (expecting "ami-...")
(neurocaas) marcustriplett@dyn-160-39-141-172 neurocaas % neurocaas-contrib remote launch-devinstance --timeout 1 --volumesize 1 --amiid "dlami18"
No instance declared, safe to deploy.
Traceback (most recent call last):
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/bin/neurocaas-contrib", line 8, in <module>
    sys.exit(main())
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/neurocaas_contrib/main.py", line 5, in main
    cli()
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/click/decorators.py", line 38, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/neurocaas_contrib/cli_commands.py", line 1363, in launch_devinstance
    ami.launch_devinstance(ami = amiid,volume_size = volumesize,timeout = timeout)
  File "/Users/marcustriplett/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/neurocaas_contrib/remote.py", line 219, in launch_devinstance
    "SecurityGroups":[self.config["Lambda"]["LambdaConfig"]["SECURITY_GROUPS"]],#[gpdict["securitygroupdevname"]],
KeyError: 'SECURITY_GROUPS'

```
The blueprint json is:
```
>> cat stack_config_template.json 
{
    "PipelineName": "circuitmap",
    "REGION": "us-east-1",
    "STAGE": "webdev",
    "Lambda": {
        "CodeUri": "../../protocols",
        "Handler": "submit_start.handler_develop",
        "Launch": true,
        "LambdaConfig": {
            "AMI": "dlami18",
            "INSTANCE_TYPE": "p2.xlarge",
            "REGION": "us-east-1",
            "IAM_ROLE": "SSMRole",
            "KEY_NAME": "testkeystack-custom-dev-key-pair",
            "WORKING_DIRECTORY": "~/bin",
            "COMMAND": "cd /home/ubuntu; neurocaas_remote/run_main.sh \"{}\" \"{}\" \"{}\" \"{}\"; . neurocaas_remote/ncap_utils/workflow.sh; cleanup"
        }
    },
    "UXData": {
        "Affiliates": [
            {
                "AffiliateName": "debuggers",
                "UserNames": [
                    "mat2245"
                ],
                "ContactEmail": "mat2245@columbia.edu"
            }
        ]
    }
}
```

**Comment by cellistigs** [comment]
Thanks for the report here! I've tested this on my end, and I believe this is a versioning issue with the NeuroCAAS contrib python package- as we discussed, this should be fixed in the most recent version of the command line tool, but I did not specify that packages should be installed in editable mode in the user documentation. Assuming you have run git pull on both repos, could you please try the following: 

```
# Remove both packages
conda activate neurocaas
pip uninstall neurocaas_contrib 
pip uninstall ncap_iac 

# Next, please update requirements to match updated versions of GitHub repos:
pip install /path/to/neurocaas/requirements.txt
pip install /path/to/neurocaas_contrib/requirements.txt

# Finally, please reinstall both python packages in editable mode: 
pip install -e /path/to/neurocaas_contrib/src
pip install -e /path/to/neurocaas
```
I believe that this should solve both issues above.

**Comment by cellistigs** [comment]
I will update the documentation to request that users install python packages in editable mode as well, thank you!
