### ISSUE TITLE
Error getting certificate

### ISSUE THREAD

**Issue by ShuonanChen** [cunningham-lab/neurocaas#12]
When I submitted a job, the output (`devami.job_output()`) shows the following:
```
neurocaas_remote/run_main_bardensr.sh workflow dirname
this is the remote directory. 
download: s3://bardensr/debuggers/results/debugjob2020-07-08 15:20:41.978100/logs/DATASET_NAME:human_cs_57.p_STATUS.txt to neurocaas_remote/ncap_utils/statusdict.json
upload: neurocaas_remote/ncap_utils/statusdict.json to s3://bardensr/debuggers/results/debugjob2020-07-08 15:20:41.978100/logs/DATASET_NAME:human_cs_57.p_STATUS.txt
2014, is the pid of the background process
Encountered AWS Error: NoSuchKey
upload: neurocaas_remote/ncap_utils/statusdict.json to s3://bardensr/debuggers/results/debugjob2020-07-08 15:20:41.978100/logs/DATASET_NAME:human_cs_57.p_STATUS.txt
copy: s3://bardensr/debuggers/configs/config.yaml to s3://bardensr/debuggers/results/debugjob2020-07-08 15:20:41.978100/process_results/config.yaml
upload: neurocaas_remote/update.txt to s3://bardensr/debuggers/results/debugjob2020-07-08 15:20:41.978100/process_results/update.txt
/var/lib/amazon/ssm/i-09e57ebffe3557d8b/document/orchestration/6916a62b-af6e-4a56-b539-18e64bbf5c21/awsrunShellScript/0.awsrunShellScript/_script.sh workflow dirname

Traceback (most recent call last):
  File "/home/ubuntu/neurocaas_remote/ncap_utils/finalcert.py", line 41, in <module>
    raise Exception("error getting certificate, not formatted for per-job logging. Message: {}".format(e))
Exception: error getting certificate, not formatted for per-job logging. Message: Traceback (most recent call last):
  File "/home/ubuntu/neurocaas_remote/ncap_utils/finalcert.py", line 30, in <module>
    c = load_cert(bucketname,certpath)
  File "/home/ubuntu/neurocaas_remote/ncap_utils/updatecert.py", line 44, in load_cert
    raise ValueError
ValueError
```

any suggestion? thank you!!!

**Comment by cellistigs** [comment]
Can you please post the submit file that you gave as input to devami.submit_job_log?

**Comment by ShuonanChen** [comment]
```
{
    "dataname": "debuggers/inputs/human_cs_57.p",
    "configname":"debuggers/configs/config.yaml",
    "instance_type": "m5.2xlarge",
    "timestamp": "07_02_20_1_23"

}
```

my `config.yaml` file is empty (just copied the first line from the examples). 
```
### Required Parameters -- If absent, an error will occur
```

**Comment by cellistigs** [comment]
It looks like the error is coming from the background logging process. I can continue looking into that- in the meantime, can you check if the data you specified has been downloaded to the location specified in the remote instance?

**Comment by ShuonanChen** [comment]
Thank you, I think it is, this is what i got:

```
$ aws s3 ls s3://bardensr --recursive
2020-07-08 15:20:58        669 debug_direct/6916a62b-af6e-4a56-b539-18e64bbf5c21/i-09e57ebffe3557d8b/awsrunShellScript/0.awsrunShellScript/stderr
2020-07-08 15:20:58       1441 debug_direct/6916a62b-af6e-4a56-b539-18e64bbf5c21/i-09e57ebffe3557d8b/awsrunShellScript/0.awsrunShellScript/stdout
2020-07-08 15:13:56        441 debug_direct/e49dc1b0-4f7c-4c06-851d-649e4ce01436/i-09e57ebffe3557d8b/awsrunShellScript/0.awsrunShellScript/stderr
2020-07-08 15:13:56        166 debug_direct/e49dc1b0-4f7c-4c06-851d-649e4ce01436/i-09e57ebffe3557d8b/awsrunShellScript/0.awsrunShellScript/stdout
2020-07-08 15:03:07        441 debug_direct/f2690bcf-b7de-43aa-ae22-128b894a86c0/i-09e57ebffe3557d8b/awsrunShellScript/0.awsrunShellScript/stderr
2020-07-08 15:03:06        166 debug_direct/f2690bcf-b7de-43aa-ae22-128b894a86c0/i-09e57ebffe3557d8b/awsrunShellScript/0.awsrunShellScript/stdout
2020-07-08 12:33:55          0 debuggers/
2020-07-08 12:34:00          0 debuggers/configs/
2020-07-08 15:01:38         42 debuggers/configs/config.yaml
2020-07-08 12:34:01          0 debuggers/inputs/
2020-07-08 15:02:45   48006415 debuggers/inputs/human_cs_57.p
2020-07-08 12:34:01          0 debuggers/results/
2020-07-08 15:03:04        227 debuggers/results/debugjob2020-07-08 15:03:03.257890/logs/DATASET_NAME:human_cs_57.p_STATUS.txt
2020-07-08 15:13:55        227 debuggers/results/debugjob2020-07-08 15:13:53.653253/logs/DATASET_NAME:human_cs_57.p_STATUS.txt
2020-07-08 15:20:54      13273 debuggers/results/debugjob2020-07-08 15:20:41.978100/logs/DATASET_NAME:human_cs_57.p_STATUS.txt
2020-07-08 15:20:54         42 debuggers/results/debugjob2020-07-08 15:20:41.978100/process_results/config.yaml
2020-07-08 15:20:55         16 debuggers/results/debugjob2020-07-08 15:20:41.978100/process_results/update.txt
2020-07-08 12:34:01          0 debuggers/submissions/
2020-07-08 12:33:55          0 logs/
2020-07-08 12:34:00          0 logs/active/
2020-07-08 12:34:00          0 logs/debugbardensr/
2020-07-08 12:34:00          0 logs/debuggers/
```

**Comment by cellistigs** [comment]
This represents the contents of the s3 bucket- please check the contents of the remote instance where you developed your algorithm. Calling submit_job_log will run the command specified in your blueprint (under [Lambda][LambdaConfig][COMMAND]) on that instance. 

Please make sure that the command specified there is executing the actions you would want it to- I.e. downloading data to from s3 to the remote instance, and running your analysis.

**Comment by ShuonanChen** [comment]
hi, i updated the scripts and it seems the data and config files are downloaded correctly.
```
aws s3 cp s3://bardensr/debuggers/inputs/human_cs_57.p input
aws s3 cp s3://bardensr/debuggers/configs/config.yaml config
download: s3://bardensr/debuggers/inputs/human_cs_57.p to tmp/input/human_cs_57.p
download: s3://bardensr/debuggers/configs/config.yaml to tmp/input/config.yaml
```

but keep getting the same error from `neurocaas_remote/ncap_utils/finalcert.py`. 
(`raise Exception("error getting certificate, not formatted for per-job logging.`)

any update on this? thanks so much!

**Comment by cellistigs** [comment]
Great. I'll open a branch for that error, but it should not impede your development and ability to generate analysis results.

**Comment by ShuonanChen** [comment]
thank you!!
