### ISSUE TITLE
`fulldeploy.sh` failed when a test user was added

### ISSUE THREAD

**Issue by ShuonanChen** [cunningham-lab/neurocaas#14]
my `UXData` in `stack_config_template.json` looks like this:
```
  "UXData": {
        "Affiliates": [
            {
                "AffiliateName": "debuggers",
                "UserNames": [
                    "tacosyne"
                ],
                "UserInput": true,
                "ContactEmail": "NOTE: KEEP THIS AFFILIATE TO ENABLE EASY TESTING"
            }
        ]
    }
```
(added `tacosyne` user as a test user) 
but then when i ran `fulldeploymen.sh` (step 6 in the documentation), it gives the error:
```
$ bash ./iac_utils/fulldeploy.sh "bardensr"
webdev
webdev mode
webdev mode
{'AffiliateName': 'debuggers', 'UserNames': ['tacosyne'], 'UserInput': True, 'ContactEmail': 'NOTE: KEEP THIS AFFILIATE TO ENABLE EASY TESTING'} affiliatedict
Error adding User tacosyne, please evaluate An error occurred (AccessDenied) when calling the GetUser operation: User: arn:aws:iam::739988523141:user/cunninghamlab/tacosyneus-east-1 is not authorized to perform: iam:GetUser on resource: user tacosyneus-east-1
Traceback (most recent call last):
  File "dev_builder.py", line 1200, in <module>
    temp =WebDevTemplate(filename)
  File "dev_builder.py", line 597, in __init__
    self.add_affiliate(affdict)
  File "dev_builder.py", line 134, in add_affiliate
    self.add_affiliate_usernet(affiliatedict)
  File "dev_builder.py", line 192, in add_affiliate_usernet
    users,usernames  = self.attach_users(affiliatedict)
  File "dev_builder.py", line 156, in attach_users
    self.iam_resource.User(user_local).create_date  # this line gives an error.
  File "/Users/Shuonan/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/boto3/resources/factory.py", line 339, in property_loader
    self.load()
  File "/Users/Shuonan/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/boto3/resources/factory.py", line 505, in do_action
    response = action(self, *args, **kwargs)
  File "/Users/Shuonan/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/boto3/resources/action.py", line 83, in __call__
    response = getattr(parent.meta.client, operation_name)(**params)
  File "/Users/Shuonan/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/Shuonan/opt/anaconda3/envs/neurocaas/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDenied) when calling the GetUser operation: User: arn:aws:iam::739988523141:user/cunninghamlab/tacosyneus-east-1 is not authorized to perform: iam:GetUser on resource: user tacosyneus-east-1

```
any suggestions? thank you!

**Comment by cellistigs** [comment]
In order to add this user, you will have to use the same developer credentials that you used to create and develop an affiliate. Please switch back your aws credentials with 
`aws configure`
Then switch back to user credentials to test data input.

**Comment by ShuonanChen** [comment]
thank you! it worked after switching back the aws credential!
